### ISSUE TITLE
Publish latest updates to npm

### ISSUE THREAD

**Issue by philwilks** [joshbirk/passport-forcedotcom#19]
A [pull request](https://github.com/joshbirk/passport-forcedotcom/pull/18) was merged last month to support an additional SalesForce parameter. We aren't yet able to use this in our application as the npm package hasn't been updated.

Would it be possible to update the npm package please?

**Comment by joshbirk** [comment]
Apologies for that - npm published (though the website is lagging) to 0.1.5.  Can you test and confirm?

**Comment by philwilks** [comment]
Thank you very much, I have tested the new 0.1.5 version on npm and it's working 👍
